### ISSUE TITLE
backgroud ,non face region restoring

### ISSUE THREAD

**Issue by maliho0803** [wzhouxiff/RestoreFormer#3]
i found that backgroud OR none face region of face image is restored not well, can you explain this?

![Screenshot_2022-06-16-17-52-45-899_com miui gallery](https://user-images.githubusercontent.com/15034804/174044635-30f8c8a5-2eb5-488a-8ec2-30bc9744d6ae.jpg)
![Screenshot_2022-06-16-17-52-41-714_com miui gallery](https://user-images.githubusercontent.com/15034804/174044649-033dfadb-1b1d-4420-adbc-4671d2344b57.jpg)

**Comment by maliho0803** [comment]
i am looking forward to your explanation

**Comment by maliho0803** [comment]
why not answer this question？

**Comment by wzhouxiff** [comment]
Most works for blind face restoration mainly focus on the face areas and pay less attention to the background areas. This work is the same and the reason that may affect the restoration of the background is that while restoring, we will match the priors of all the areas of the face image, including the areas of background, from HQ Dictionary, which is learned from high-quality face images. However, different from the face areas that have strong commonalities between different faces, the background of different images is diverse. It is hard to attain highly similar priors for the background of a specific face image. Besides, as described in the paper, we found that the skip connection in the MHCA happens between the attended feature and the priors rather than the degraded feature can attain better restored results in the face areas, which may loss the information of the original background to some extend.
